run:
  timeout: 5m

issues:
  exclude-dirs:
    - tests/mocks
    - tests/fixtures  
  exclude-files:
    - ".*_test.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    # Exclude typecheck errors for known packages with false positives
    - linters:
        - typecheck
      text: "undefined: (validator|excelize)"
    - linters: 
        - typecheck
      text: "WithFields undefined"
    - linters: 
        - typecheck
      text: "WithError undefined"

linters-settings:
  gocyclo:
    min-complexity: 30
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true
  errcheck:
    check-type-assertions: true
    check-blank: false
  gofmt:
    simplify: true
  gosec:
    severity: medium
    confidence: medium
  misspell:
    locale: US
    ignore-words:
      - descripcion
      - configuracion
      - comando
      - columnas
      - invalidas
      - informativo
      - directorios
      - presentes
  lll:
    line-length: 120

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - gosimple
    - goconst
    - gocyclo
    - unused
    - ineffassign
    - staticcheck
    - misspell
    - gosec
    - unconvert
    - unparam

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true