run:
  timeout: 5m
  skip-dirs:
    - tests/mocks
    - tests/fixtures
  skip-files:
    - ".*_test.go$"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    # Exclude typecheck errors for known packages with false positives
    - linters:
        - typecheck
      text: "undefined: (validator|excelize)"
    - linters: 
        - typecheck
      text: "WithFields undefined"

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true
  errcheck:
    check-type-assertions: true
    check-blank: false
  gofmt:
    simplify: true
  gosec:
    severity: medium
    confidence: medium
  misspell:
    locale: US
  lll:
    line-length: 120

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - gosimple
    - goconst
    - gocyclo
    - unused
    - ineffassign
    - staticcheck
    - misspell
    - gosec
    - unconvert
    - unparam

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true